# -*- coding: utf-8 -*-
"""meu-app.ipy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T1nZ3V90066Z_LozkiEHuh9SdLb7JNf2
"""

import streamlit as st
from prophet import Prophet
import pandas as pd
from datetime import datetime, timedelta

# Carregar os dados
@st.cache
def load_data():
    # Carregar os dados preenchidos para frente
    df_filled_forward = pd.read_csv('df_filled_forward.csv')
    return df_filled_forward

# Ajustar o modelo Prophet
def fit_prophet_model(data):
    model = Prophet()
    model.fit(data)
    return model

# Fazer previsões
def make_predictions(model, periods):
    future = model.make_future_dataframe(periods=periods)
    forecast = model.predict(future)
    return forecast

# Função principal do aplicativo
def main():
    # Título do aplicativo
    st.title('Previsão do Preço do Petróleo Brent')

    # Carregar os dados
    df = load_data()

    # Ajustar o modelo Prophet
    model = fit_prophet_model(df)

    # Selecionar período para fazer previsões
    st.subheader('Selecionar Período para Previsões')
    periods = st.slider('Número de Dias para Previsão:', min_value=1, max_value=365, value=30)

    # Fazer previsões
    forecast = make_predictions(model, periods)

    # Exibir previsões
    st.subheader('Previsões para os Próximos {} Dias:'.format(periods))
    st.write(forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(periods))

if __name__ == '__main__':
    main()