# -*- coding: utf-8 -*-
"""meu-app.ipy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T1nZ3V90066Z_LozkiEHuh9SdLb7JNf2
"""

import streamlit as st
import pandas as pd
from prophet import Prophet
import altair as alt

# Carregar os dados (substitua este trecho pelo seu código de carregamento de dados)
@st.cache
def load_data():
    # Carregar o dataframe df_filled_forward
    df = pd.read_csv('df_filled_forward.csv')
    return df

# Função para prever os preços usando o Prophet
def predict_prices(df):
    # Criar um dataframe para o Prophet
    df_prophet = df.rename(columns={'Date': 'ds', 'Preço': 'y'})

    # Inicializar e treinar o modelo
    model = Prophet()
    model.fit(df_prophet)

    # Fazer previsões para os próximos n dias
    future = model.make_future_dataframe(periods=360)
    forecast = model.predict(future)

    return forecast

# Carregar os dados
df = load_data()

# Título do app
st.title('Previsão de Preços do Petróleo usando Prophet')

# Prever os preços e exibir o resultado
forecast = predict_prices(df)
st.write(forecast)

# Criar um gráfico interativo com Altair
st.subheader('Gráfico Interativo')

# Plotar o gráfico de previsão
c = alt.Chart(forecast).mark_line().encode(
    x='ds',
    y='yhat',
    tooltip=['ds', 'yhat'],
    color=alt.value('blue')
).properties(
    width=800,
    height=400
).interactive()

# Adicionar título e rótulos aos eixos
c = c.properties(
    title='Previsão de Preços do Petróleo',
).configure_axis(
    titleFontSize=14,
    labelFontSize=12
)

# Exibir o gráfico
st.altair_chart(c)